-- 1. Profiles Table (Players)
create table profiles (
  id uuid references auth.users not null primary key, -- Linked to Supabase Auth User
  team_id uuid, -- Can be null for now
  name text not null,
  position text,
  height numeric, -- cm
  weight numeric, -- kg
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Index for Team Filter
create index idx_profiles_team on profiles(team_id);


-- 2. Measurements Table (Time-Series Data)
-- Stores all test results (Jump, Strength, Sprint) in a flexible JSONB 'metrics' column
create table measurements (
  id bigint generated by default as identity primary key,
  player_id uuid references profiles(id) not null,
  test_type text not null, -- 'CMJ', 'SJ', 'Nordbord', 'Sprint_10m', etc.
  recorded_at timestamp with time zone not null,
  metrics jsonb not null, -- e.g. {"height": 45.5, "power": 3200}
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Performance Indexes (CRITICAL)

-- A. Player History Index: Makes "Get me all CMJ jumps for Player X" instant.
create index idx_measurements_player_date 
  on measurements (player_id, recorded_at desc);

-- B. Recent Activity Index: Makes "Show me the last 50 tests in the center" instant.
create index idx_measurements_date 
  on measurements (recorded_at desc);

-- C. JSONB Index: Allows fast filtering inside the JSON metrics (e.g. "Find jumps > 50cm")
create index idx_measurements_type_metrics 
  on measurements using gin (metrics);


-- 4. Row Level Security (RLS) Policies

alter table profiles enable row level security;
alter table measurements enable row level security;

-- Policy: Allow read access to all authenticated users (Coaches/Staff)
create policy "Allow read access for authenticated users"
  on profiles for select
  to authenticated
  using (true);

create policy "Allow read access for measurements"
  on measurements for select
  to authenticated
  using (true);

-- Policy: Allow insert/update for authenticated users (Staff)
create policy "Allow insert for authenticated users"
  on measurements for insert
  to authenticated
  with check (true);
